# Generated by Django 5.0.4 on 2024-04-28 03:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cleaner', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='clean',
        ),
        migrations.RemoveField(
            model_name='comment',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='comment',
            name='updated_at',
        ),
        migrations.AddField(
            model_name='comment',
            name='book',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='cleaner.cleaners'),
            preserve_default=False,
        ),
    ]
